version: '2'
catalog:
  name: "WordPress FIFA55"
  version: "v0.4 Acaz"
  description: "Blog tool, publishing platform and CMS based on bitnami images"
  uuid: WordPress-1
  minimum_rancher_version: v0.51.0
  questions:
    - variable: public_port
      description: "public port to access the WordPress site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: mariadb_host
      description: "MariaDB host"
      label: "MariaDB Host"
      required: true
      default: "mariadb_host"
      type: "string"
    - variable: mariadb_root_password
      description: "MariaDB root password, set on first run"
      label: "MariaDB Root Password"
      required: true
      default: "mariadb_my_root"
      type: "string"
    - variable: mariadb_database_name
      description: "WordPress database name"
      label: "WordPress database name"
      required: true
      default: "bitnami_wordpress"
      type: "string"
    - variable: wordpress_username
      description: "WordPress application username"
      label: "WordPress application username"
      required: true
      default: "admin"
      type: "string"
    - variable: wordpress_password
      description: "WordPress application password"
      label: "WordPress application password"
      required: true
      default: "bitnami"
      type: "string"
    - variable: volume_driver
      description: "Volume driver to use with this service"
      label: "Volume driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
services:
  wordpress:
    scale: 1
    retain_ip: true
    health_check:
      port: 80
      interval: 30000
      unhealthy_threshold: 3
      request_line: 'GET / HTTP/1.0'
      healthy_threshold: 2
      response_timeout: 5000
